// All 260 prompts transcribed mechanically from
// prompt-library-content.md (Phase 6 handoff) — do not paraphrase when
// editing; if a prompt needs improving, fix the source markdown first so
// the two stay in sync, then re-transcribe. Legal/Finance disclaimers in
// parentheses are part of the prompt text on purpose — do not strip them.
export const PROMPT_LIBRARY = {
  enterprise: {
    label: "Enterprise",
    categories: [
      {
        id: "management",
        label: "Management",
        prompts: [
          { id: "management-01", label: "Team meeting agenda", text: "Create a 30-minute team meeting agenda for [topic], including time allocations, discussion questions, and a decision to be made by the end." },
          { id: "management-02", label: "Delegating a task", text: "Help me write a delegation message to a direct report for the following task: [task]. Include the objective, deadline, resources available, and how success will be measured." },
          { id: "management-03", label: "Performance review draft", text: "Draft a performance review summary for an employee who [describe performance], covering strengths, areas for growth, and 2-3 specific goals for next quarter." },
          { id: "management-04", label: "Preparing for a difficult conversation", text: "Help me prepare talking points for a difficult conversation with [role/person] about [issue]. I want to be direct but supportive." },
          { id: "management-05", label: "Prioritizing competing tasks", text: "I have the following list of tasks/projects: [list]. Help me prioritize them using [framework, e.g. impact vs. effort] and explain the reasoning." },
          { id: "management-06", label: "One-on-one questions", text: "Give me 10 thoughtful one-on-one questions to ask a direct report who [context, e.g. seems disengaged / is a new hire / is a high performer]." },
          { id: "management-07", label: "Announcing a change", text: "Draft an announcement to my team about [organizational change], addressing what's changing, why, what stays the same, and what to expect next." },
          { id: "management-08", label: "Working through a decision", text: "Help me think through a decision about [decision]. Lay out the key options, the tradeoffs of each, and what additional information I should gather before deciding." },
          { id: "management-09", label: "30-60-90 day plan", text: "Create a 30-60-90 day onboarding plan for a new [role] joining my team, with milestones and check-in points." },
          { id: "management-10", label: "Mediating a conflict", text: "Two team members are in conflict over [issue]. Help me think through how to mediate this fairly, including questions to ask each person." },
        ],
      },
      {
        id: "finance-and-accounting",
        label: "Finance and Accounting",
        prompts: [
          { id: "finance-and-accounting-01", label: "Explaining a budget variance", text: "Explain the likely causes of a budget variance where [department/category] spent [X]% over/under budget in [period], and suggest questions to investigate further." },
          { id: "finance-and-accounting-02", label: "Expense policy draft", text: "Draft a clear, employee-friendly expense reimbursement policy covering travel, meals, and equipment purchases." },
          { id: "finance-and-accounting-03", label: "Plain-language financial summary", text: "Summarize this financial data in plain language for a non-finance audience: [paste data]. Highlight the 3 most important takeaways." },
          { id: "finance-and-accounting-04", label: "Overdue invoice follow-up", text: "Write a polite but firm follow-up email to a client whose invoice is [X] days overdue." },
          { id: "finance-and-accounting-05", label: "Cost-cutting ideas", text: "Suggest 10 realistic ways a [company size/industry] company could reduce operating costs without cutting staff." },
          { id: "finance-and-accounting-06", label: "Forecast assumptions checklist", text: "Help me list the key assumptions I should document when building a [timeframe] revenue forecast for [business type]." },
          { id: "finance-and-accounting-07", label: "Vendor payment terms negotiation", text: "Help me draft talking points to negotiate better payment terms with a vendor we've worked with for [X years]." },
          { id: "finance-and-accounting-08", label: "Financial report structure", text: "Outline a clear structure for a quarterly financial report to [audience, e.g. the board / investors / leadership team]." },
          { id: "finance-and-accounting-09", label: "Month-end close checklist", text: "Create a month-end close checklist for a small business, covering bank reconciliation, accruals, and reporting." },
          { id: "finance-and-accounting-10", label: "Explaining a finance term", text: "Explain [financial concept, e.g. deferred revenue, EBITDA, working capital] in plain language with a simple example." },
        ],
      },
      {
        id: "marketing-and-sales",
        label: "Marketing and Sales",
        prompts: [
          { id: "marketing-and-sales-01", label: "Campaign brief", text: "Write a campaign brief for a [channel] campaign promoting [product/service] to [audience], including goal, key message, and success metrics." },
          { id: "marketing-and-sales-02", label: "Cold outreach email", text: "Write a cold outreach email to [target persona] introducing [product/service], focused on their likely pain point of [pain point]." },
          { id: "marketing-and-sales-03", label: "Handling sales objections", text: "Help me prepare responses to the 5 most common objections a prospect might raise about [product/service/price point]." },
          { id: "marketing-and-sales-04", label: "Social post variations", text: "Write 5 social media post variations announcing [announcement] for [platform], each with a different angle or hook." },
          { id: "marketing-and-sales-05", label: "Customer persona", text: "Build a customer persona for [product/service] targeting [rough audience description], including goals, frustrations, and where they spend time online." },
          { id: "marketing-and-sales-06", label: "Lead follow-up sequence", text: "Draft a 3-email follow-up sequence for a lead who [action taken, e.g. downloaded a resource / attended a demo] but hasn't responded." },
          { id: "marketing-and-sales-07", label: "Competitive positioning", text: "Help me draft messaging that positions [my product] against [competitor] without naming them directly, focused on [differentiator]." },
          { id: "marketing-and-sales-08", label: "Case study outline", text: "Outline a customer case study about [customer/result], structured as challenge, solution, and results." },
          { id: "marketing-and-sales-09", label: "Sales call prep", text: "Help me prepare for a sales call with [prospect type], including discovery questions and what to listen for." },
          { id: "marketing-and-sales-10", label: "Pricing page copy", text: "Write clear, benefit-focused copy for a pricing page with [X] tiers: [tier names/prices], each with 3-4 key features." },
        ],
      },
      {
        id: "human-resources",
        label: "Human Resources",
        prompts: [
          { id: "human-resources-01", label: "Job description", text: "Write a job description for a [role title] at a [company size/industry] company, including responsibilities, requirements, and a compelling first paragraph." },
          { id: "human-resources-02", label: "Behavioral interview questions", text: "Give me 10 behavioral interview questions to assess [skill/trait, e.g. ownership, collaboration, adaptability] for a [role] candidate." },
          { id: "human-resources-03", label: "Offer letter summary", text: "Help me write a warm, clear offer letter summary email to a candidate for [role], including next steps." },
          { id: "human-resources-04", label: "Plain-language policy explanation", text: "Explain our [policy, e.g. PTO, remote work, parental leave] policy in plain, friendly language for a new employee handbook." },
          { id: "human-resources-05", label: "Exit interview questions", text: "Give me 10 thoughtful exit interview questions that go beyond \"why are you leaving\" to surface real feedback." },
          { id: "human-resources-06", label: "Employee recognition message", text: "Write a short, specific recognition message for an employee who [accomplishment]." },
          { id: "human-resources-07", label: "Difficult HR conversation prep", text: "Help me prepare talking points for a conversation with an employee about [issue, e.g. attendance, performance, conduct], keeping it fair and documented." },
          { id: "human-resources-08", label: "Engagement survey questions", text: "Draft 10 employee engagement survey questions covering workload, management, and growth opportunities." },
          { id: "human-resources-09", label: "DEI initiative ideas", text: "Suggest 10 practical, low-cost initiatives a [company size] company could implement to improve workplace inclusion." },
          { id: "human-resources-10", label: "Return-to-office announcement", text: "Draft an announcement about [policy change, e.g. hybrid schedule change] that explains the reasoning and addresses likely employee concerns." },
        ],
      },
      {
        id: "operations",
        label: "Operations",
        prompts: [
          { id: "operations-01", label: "Turning a process into an SOP", text: "Help me turn this rough description of a process into a clear, step-by-step SOP: [describe process]." },
          { id: "operations-02", label: "Bottleneck analysis", text: "I'm seeing delays in [process/workflow]. Help me think through likely bottlenecks and questions to investigate." },
          { id: "operations-03", label: "Vendor comparison framework", text: "Help me build a comparison framework to evaluate vendors for [service/tool], including the criteria I should weigh." },
          { id: "operations-04", label: "Supply issue troubleshooting", text: "Suggest a troubleshooting checklist for recurring [inventory/supply chain issue, e.g. stockouts, late deliveries]." },
          { id: "operations-05", label: "Choosing KPIs", text: "Help me identify the 5-7 most important KPIs to track for [operations area, e.g. fulfillment, customer support, manufacturing]." },
          { id: "operations-06", label: "SOP review", text: "Review this SOP for gaps or unclear steps: [paste SOP]." },
          { id: "operations-07", label: "Capacity planning", text: "Help me think through capacity planning for [team/resource] given [expected growth/demand]." },
          { id: "operations-08", label: "Incident post-mortem", text: "Help me structure a post-mortem for an operational incident involving [what happened], covering root cause, impact, and prevention." },
          { id: "operations-09", label: "Cross-team handoff template", text: "Draft a clear handoff document template for when work moves from [team A] to [team B]." },
          { id: "operations-10", label: "Efficiency audit questions", text: "Suggest questions to ask during an efficiency audit of [process], to identify waste or redundant steps." },
        ],
      },
      {
        id: "information-technology",
        label: "Information Technology",
        prompts: [
          { id: "information-technology-01", label: "Incident summary for stakeholders", text: "Write a clear, non-technical incident summary for stakeholders about an outage affecting [system], including impact, cause, and resolution." },
          { id: "information-technology-02", label: "Access request policy", text: "Draft a simple access request and approval policy for [system/tool] at a [company size] company." },
          { id: "information-technology-03", label: "Troubleshooting guide", text: "Turn this list of common issues into a troubleshooting guide for end users: [list issues]." },
          { id: "information-technology-04", label: "Security awareness reminder", text: "Write a short, non-alarming security awareness reminder about [topic, e.g. phishing, password hygiene] for all employees." },
          { id: "information-technology-05", label: "Vendor evaluation questions", text: "Give me a list of technical and security questions to ask when evaluating a new [type of software] vendor." },
          { id: "information-technology-06", label: "Change management notice", text: "Draft a heads-up notice to users about an upcoming [system change/maintenance window], including what to expect and who to contact." },
          { id: "information-technology-07", label: "IT onboarding checklist", text: "Create an IT onboarding checklist for a new employee's first day, covering accounts, hardware, and access." },
          { id: "information-technology-08", label: "Improving technical documentation", text: "Review this technical documentation and suggest where it needs more clarity for a non-expert reader: [paste doc]." },
          { id: "information-technology-09", label: "Blameless postmortem template", text: "Help me draft a blameless postmortem template for system downtime incidents." },
          { id: "information-technology-10", label: "Explaining a technical concept", text: "Explain [technical concept, e.g. zero trust, load balancing, containerization] in plain language for a non-technical stakeholder." },
        ],
      },
      {
        id: "customer-service",
        label: "Customer Service",
        prompts: [
          { id: "customer-service-01", label: "Empathetic response to an upset customer", text: "Help me write an empathetic response to a customer who is upset about [issue], acknowledging their frustration without over-promising." },
          { id: "customer-service-02", label: "FAQ draft", text: "Draft FAQ answers for the following common customer questions: [list questions]." },
          { id: "customer-service-03", label: "Apology email", text: "Write a sincere apology email to a customer affected by [service issue], including what we're doing to fix it." },
          { id: "customer-service-04", label: "De-escalation talking points", text: "Give me talking points to de-escalate a call with an angry customer about [issue] while staying within policy." },
          { id: "customer-service-05", label: "Explaining a refund policy", text: "Help me explain our refund policy to a customer in a way that's clear but not robotic." },
          { id: "customer-service-06", label: "Support response template", text: "Write a friendly, reusable response template for the common support request: [request type]." },
          { id: "customer-service-07", label: "Summarizing customer feedback", text: "Summarize the themes in this batch of customer feedback: [paste feedback], and suggest the top 3 issues to address." },
          { id: "customer-service-08", label: "Win-back email", text: "Draft a win-back email to a customer who canceled [product/service], addressing a likely reason without being pushy." },
          { id: "customer-service-09", label: "Internal escalation note", text: "Help me write a clear internal escalation summary for a customer issue that needs manager attention: [describe issue]." },
          { id: "customer-service-10", label: "Responding to a positive review", text: "Write a genuine, non-generic response to a positive customer review that mentions [specific detail from review]." },
        ],
      },
      {
        id: "research-and-development",
        label: "Research and Development",
        prompts: [
          { id: "research-and-development-01", label: "Literature summary", text: "Summarize the key findings and open questions from this research area: [topic], as if explaining to a colleague outside the field." },
          { id: "research-and-development-02", label: "Experiment design", text: "Help me think through the design of an experiment to test [hypothesis], including variables to control and potential confounds." },
          { id: "research-and-development-03", label: "Technical spec review", text: "Review this technical specification for gaps, ambiguities, or unstated assumptions: [paste spec]." },
          { id: "research-and-development-04", label: "Prior art research framing", text: "Help me identify search terms and angles to research prior art or existing solutions for [problem/idea]." },
          { id: "research-and-development-05", label: "Technical risk assessment", text: "Help me think through the technical risks of pursuing [approach/technology] for [project], and how to mitigate the top ones." },
          { id: "research-and-development-06", label: "Plain-language research brief", text: "Turn this technical research summary into a plain-language brief for non-technical stakeholders: [paste summary]." },
          { id: "research-and-development-07", label: "Hypothesis generation", text: "Given this problem: [problem], help me generate 5-7 distinct hypotheses worth testing." },
          { id: "research-and-development-08", label: "Invention disclosure draft", text: "Help me draft a rough invention disclosure summary for [idea], covering the problem, the solution, and what's novel about it." },
          { id: "research-and-development-09", label: "Peer review feedback", text: "Give me structured feedback on the clarity and rigor of this research summary: [paste summary]." },
          { id: "research-and-development-10", label: "Prioritizing R&D initiatives", text: "Help me prioritize this list of R&D initiatives based on impact, feasibility, and strategic fit: [list initiatives]." },
        ],
      },
      {
        id: "legal",
        label: "Legal",
        prompts: [
          { id: "legal-01", label: "Plain-language contract summary", text: "Summarize this contract in plain language, highlighting key obligations, deadlines, and any unusual clauses: [paste contract text]. (Not a substitute for legal review.)" },
          { id: "legal-02", label: "Rewriting a policy in plain language", text: "Rewrite this policy in clearer, more accessible language while preserving its meaning: [paste policy]." },
          { id: "legal-03", label: "NDA review questions", text: "Help me prepare questions to ask counsel about a mutual NDA before signing, based on this draft: [paste draft]." },
          { id: "legal-04", label: "General compliance checklist", text: "Help me build a general compliance checklist for [regulation/area, e.g. data privacy, workplace safety] appropriate for a [company size] company. (Verify with counsel.)" },
          { id: "legal-05", label: "Contract negotiation prep", text: "Help me identify which clauses in this contract are most important to negotiate, and why: [paste contract]." },
          { id: "legal-06", label: "Requesting a legal review", text: "Help me write a clear internal request to legal explaining what I need reviewed and by when, for [situation]." },
          { id: "legal-07", label: "Terms of service summary", text: "Summarize this terms of service document into the 5 things a user most needs to know: [paste terms]." },
          { id: "legal-08", label: "Factual dispute summary", text: "Help me write a clear, factual summary of a dispute with [party] for internal records, sticking to facts and avoiding speculation." },
          { id: "legal-09", label: "Flagging risky language", text: "Review this document and flag any language that seems risky or worth a second look from counsel: [paste document]." },
          { id: "legal-10", label: "Employee-facing legal explainer", text: "Explain [legal concept relevant to employees, e.g. at-will employment, non-compete basics] in plain language. (General information, not legal advice.)" },
        ],
      },
    ],
  },
  personal: {
    label: "Personal",
    categories: [
      {
        id: "cooking-baking",
        label: "Cooking/Baking",
        prompts: [
          { id: "cooking-baking-01", label: "What can I make?", text: "I have [list ingredients] in my kitchen. Suggest 3 recipes I could make with what I have, noting anything I'd need to buy." },
          { id: "cooking-baking-02", label: "Scaling a recipe", text: "Help me scale this recipe from [X] servings to [Y] servings, adjusting all ingredient quantities: [paste recipe]." },
          { id: "cooking-baking-03", label: "Ingredient substitution", text: "I'm out of [ingredient] for this recipe: [paste recipe]. What can I substitute, and how will it change the result?" },
          { id: "cooking-baking-04", label: "Weekly meal plan", text: "Create a 5-day dinner meal plan for [X] people that's [constraint, e.g. vegetarian, quick, budget-friendly], with a consolidated grocery list." },
          { id: "cooking-baking-05", label: "Baking troubleshooting", text: "My [baked good] keeps turning out [problem, e.g. dense, dry, flat]. Help me troubleshoot what might be going wrong." },
          { id: "cooking-baking-06", label: "Flavor pairing ideas", text: "Suggest flavor pairings and a simple dish idea built around [main ingredient]." },
          { id: "cooking-baking-07", label: "Explaining a technique", text: "Explain how to properly [technique, e.g. fold egg whites, temper chocolate, deglaze a pan] for a home cook." },
          { id: "cooking-baking-08", label: "Reinventing leftovers", text: "I have leftover [dish/ingredient]. Suggest 3 different ways to turn it into a new meal." },
          { id: "cooking-baking-09", label: "Dinner party menu", text: "Help me plan a 3-course dinner party menu for [X] guests with [dietary restriction], including a rough prep timeline." },
          { id: "cooking-baking-10", label: "Intro to a cuisine", text: "Give me a beginner-friendly introduction to [cuisine]'s core flavors and techniques, with 2-3 dishes to start with." },
        ],
      },
      {
        id: "reading",
        label: "Reading",
        prompts: [
          { id: "reading-01", label: "Book recommendations", text: "Recommend 5 books similar to [book/author I liked], and explain why each one fits." },
          { id: "reading-02", label: "Themed reading list", text: "Build me a reading list of 6 books exploring [theme/topic], mixing fiction and nonfiction." },
          { id: "reading-03", label: "Book club discussion questions", text: "Generate 8 thoughtful discussion questions for a book club reading [book title]." },
          { id: "reading-04", label: "Spoiler-free overview", text: "Give me a spoiler-free overview of [book] — premise, tone, and who would enjoy it — without revealing major plot points." },
          { id: "reading-05", label: "12-book reading challenge", text: "Design a themed 12-book reading challenge for the year around [interest/theme]." },
          { id: "reading-06", label: "Comparing two books", text: "Compare [book A] and [book B] in terms of themes, style, and which one might suit me better given I enjoyed [reference book]." },
          { id: "reading-07", label: "Author deep-dive", text: "Give me an overview of [author]'s work and recommend where a new reader should start." },
          { id: "reading-08", label: "Realistic reading schedule", text: "Help me build a realistic reading schedule to finish [book, X pages] in [timeframe]." },
          { id: "reading-09", label: "Exploring a new genre", text: "I mostly read [genre]. Suggest 5 books from a different genre that might still appeal to me and explain the connection." },
          { id: "reading-10", label: "Note-taking system", text: "Suggest a simple note-taking or annotation system for retaining more from nonfiction books I read." },
        ],
      },
      {
        id: "pets",
        label: "Pets",
        prompts: [
          { id: "pets-01", label: "Researching a new pet", text: "I'm considering getting a [type of pet/breed]. Help me understand the realistic time, cost, and space commitment involved." },
          { id: "pets-02", label: "Simple training plan", text: "Help me create a simple training plan to teach my [pet type] to [behavior, e.g. stop jumping, come when called]." },
          { id: "pets-03", label: "Behavior troubleshooting", text: "My [pet type] has started [behavior issue]. Suggest possible causes and a reasonable first step (and when to see a vet/trainer)." },
          { id: "pets-04", label: "Indoor enrichment ideas", text: "Suggest 8 low-cost enrichment activities to keep my [pet type] mentally stimulated indoors." },
          { id: "pets-05", label: "Diet questions for the vet", text: "Help me understand what to look for in a good [pet type] food, and questions to ask my vet about diet." },
          { id: "pets-06", label: "Traveling with a pet", text: "Help me build a checklist for traveling with my [pet type] by [car/plane] for [trip length]." },
          { id: "pets-07", label: "Introducing pets to each other", text: "Suggest a gradual plan for introducing a new [pet type] to my existing [pet type] at home." },
          { id: "pets-08", label: "Pet-proofing a home", text: "Give me a room-by-room checklist for pet-proofing a home for a [pet type, e.g. curious puppy, climbing cat]." },
          { id: "pets-09", label: "Senior pet care", text: "Suggest what to watch for and how to adjust care as my [pet type] gets older." },
          { id: "pets-10", label: "Explaining a vet term", text: "Explain [vet term/diagnosis] in plain language, including general next-step questions to ask my vet." },
        ],
      },
      {
        id: "video-gaming",
        label: "Video Gaming",
        prompts: [
          { id: "video-gaming-01", label: "Similar game recommendations", text: "I enjoyed [game], recommend 5 similar games and explain what makes each one similar." },
          { id: "video-gaming-02", label: "Build/strategy help", text: "Help me think through a strong build/strategy for [character/class] in [game], given I prefer [playstyle]." },
          { id: "video-gaming-03", label: "Backlog prioritization", text: "Here's my game backlog: [list games]. Help me prioritize what to play next based on [mood/time available]." },
          { id: "video-gaming-04", label: "Co-op game finder", text: "Suggest 5 good co-op games for [X] players that are easy to pick up, for a [casual/hardcore] group." },
          { id: "video-gaming-05", label: "Explaining a game mechanic", text: "Explain how [mechanic, e.g. crafting system, skill tree] works in [game] in simple terms." },
          { id: "video-gaming-06", label: "Planning a game night", text: "Help me plan a game night with friends — suggest 3 games that fit [group size] and [time available]." },
          { id: "video-gaming-07", label: "Entering a new genre", text: "I've never played [genre]. Recommend a beginner-friendly entry point and what to expect." },
          { id: "video-gaming-08", label: "Stuck on a puzzle", text: "I'm stuck on [describe the puzzle/level] in [game]. Give me a hint without fully spoiling the solution." },
          { id: "video-gaming-09", label: "Gaming setup advice", text: "Help me think through what to prioritize for a [budget] gaming setup upgrade, given I mainly play [game types]." },
          { id: "video-gaming-10", label: "Catching up on lore", text: "Give me a clear summary of the story/lore in [game/series] so far, without needing to have played every entry." },
        ],
      },
      {
        id: "outdoor-activities",
        label: "Outdoor Activities",
        prompts: [
          { id: "outdoor-activities-01", label: "Planning a hike", text: "Help me plan a [difficulty level] hike near [location] for [group type], including what to bring." },
          { id: "outdoor-activities-02", label: "Gear checklist", text: "Create a gear checklist for [activity, e.g. car camping, day hiking, backpacking] in [season/conditions]." },
          { id: "outdoor-activities-03", label: "Two-day itinerary", text: "Build a rough 2-day outdoor itinerary near [location] focused on [activity type]." },
          { id: "outdoor-activities-04", label: "Weather-based planning", text: "Given [weather conditions], suggest what outdoor activities are realistic and what precautions to take." },
          { id: "outdoor-activities-05", label: "Beginner skill progression", text: "Help me build a beginner progression plan to get better at [activity, e.g. rock climbing, trail running]." },
          { id: "outdoor-activities-06", label: "Solo trip safety checklist", text: "Give me a safety checklist to review before a solo [activity] trip." },
          { id: "outdoor-activities-07", label: "Family-friendly ideas", text: "Suggest 8 outdoor activities near [location/type of area] suitable for a family with kids ages [ages]." },
          { id: "outdoor-activities-08", label: "Photography-friendly spots and timing", text: "Suggest what times of day and conditions would be best for photographing [type of landscape/subject] outdoors." },
          { id: "outdoor-activities-09", label: "Post-activity recovery", text: "Suggest a simple recovery routine after a long day of [activity]." },
          { id: "outdoor-activities-10", label: "Learning to identify nature", text: "Help me get started identifying common [birds/plants/trees] I might see while [activity] in [region]." },
        ],
      },
      {
        id: "traveling",
        label: "Traveling",
        prompts: [
          { id: "traveling-01", label: "Trip itinerary", text: "Plan a [X]-day itinerary for [destination] for [traveler type], balancing [interests, e.g. food, history, relaxation]." },
          { id: "traveling-02", label: "Packing list", text: "Create a packing list for a [X]-day trip to [destination] in [season], for [activity type]." },
          { id: "traveling-03", label: "Trip budget breakdown", text: "Help me build a rough budget breakdown for a [X]-day trip to [destination] covering flights, lodging, food, and activities." },
          { id: "traveling-04", label: "Local customs and etiquette", text: "What should I know about local customs and etiquette before visiting [destination]?" },
          { id: "traveling-05", label: "Off-the-beaten-path suggestions", text: "Suggest 5 lesser-known spots in [destination] beyond the typical tourist highlights." },
          { id: "traveling-06", label: "Planning a long travel day", text: "Help me plan for a long travel day involving [flights/layovers], including what to pack in my carry-on." },
          { id: "traveling-07", label: "Essential travel phrases", text: "Give me the 15 most useful phrases to know in [language] for a short trip." },
          { id: "traveling-08", label: "Comparing two destinations", text: "Compare [destination A] and [destination B] for a trip focused on [interest], and help me decide." },
          { id: "traveling-09", label: "Solo travel safety", text: "Suggest general safety considerations for solo travel in [destination]." },
          { id: "traveling-10", label: "Post-trip reflection prompts", text: "Give me 5 reflective journal prompts to capture memories after a trip to [destination]." },
        ],
      },
      {
        id: "socializing",
        label: "Socializing",
        prompts: [
          { id: "socializing-01", label: "Conversation starters", text: "Give me 10 genuine conversation starters for [context, e.g. a work networking event, a first date, meeting new neighbors]." },
          { id: "socializing-02", label: "Hosting a low-stress gathering", text: "Help me plan a low-stress get-together for [X] people, including food, activities, and timing." },
          { id: "socializing-03", label: "Reconnecting with an old friend", text: "Help me write a warm, low-pressure message to reconnect with an old friend I've lost touch with." },
          { id: "socializing-04", label: "Handling an awkward situation", text: "Suggest a few graceful ways to handle [awkward social situation]." },
          { id: "socializing-05", label: "Icebreaker activities", text: "Suggest 5 icebreaker activities for a group of [X] people who [mostly know/don't know each other]." },
          { id: "socializing-06", label: "Deepening a conversation", text: "Give me a few questions that can move a conversation from small talk to something more meaningful, without being intense." },
          { id: "socializing-07", label: "Declining an invitation kindly", text: "Help me write a kind but clear message declining an invitation to [event] without over-explaining." },
          { id: "socializing-08", label: "Making new friends as an adult", text: "Suggest realistic ways to meet new people who share my interest in [hobby/interest] as an adult." },
          { id: "socializing-09", label: "Coordinating a group trip", text: "Help me draft a message to coordinate a group trip/outing with friends, including key decisions we need to make." },
          { id: "socializing-10", label: "Writing a toast or speech", text: "Help me write a short, genuine toast for [occasion, e.g. a friend's wedding, a retirement party]." },
        ],
      },
      {
        id: "diy-arts-crafts",
        label: "DIY/Arts & Crafts",
        prompts: [
          { id: "diy-arts-crafts-01", label: "Project idea generator", text: "Suggest 5 beginner-friendly [craft type, e.g. woodworking, knitting, painting] projects using [materials I have or want to use]." },
          { id: "diy-arts-crafts-02", label: "Step-by-step project guide", text: "Give me a clear, step-by-step guide for [project], including materials needed and common mistakes to avoid." },
          { id: "diy-arts-crafts-03", label: "Troubleshooting a project", text: "My [project] isn't turning out right — [describe issue]. Help me figure out what went wrong." },
          { id: "diy-arts-crafts-04", label: "Material substitution", text: "I don't have [material] for this project. What could I use instead, and how would it change the result?" },
          { id: "diy-arts-crafts-05", label: "Upcycling idea", text: "Suggest 3 ways I could upcycle [item] into something useful or decorative." },
          { id: "diy-arts-crafts-06", label: "Beginner skill progression", text: "I'm a beginner at [craft]. Suggest a progression of projects to build my skills over time." },
          { id: "diy-arts-crafts-07", label: "Handmade gift ideas", text: "Suggest a handmade gift project for [recipient/occasion] that's achievable in [time available]." },
          { id: "diy-arts-crafts-08", label: "Starter tool/supply list", text: "What's a reasonable starter tool/supply list for getting into [craft] without overspending?" },
          { id: "diy-arts-crafts-09", label: "Color/design help", text: "Help me think through a color palette or design approach for [project description]." },
          { id: "diy-arts-crafts-10", label: "Organizing a craft space", text: "Suggest ideas for organizing a small [craft/workshop] space in [room type/size]." },
        ],
      },
      {
        id: "board-card-games",
        label: "Board/Card Games",
        prompts: [
          { id: "board-card-games-01", label: "Game night recommendations", text: "Suggest 5 board games for a group of [X] people with [experience level], that play in under [time]." },
          { id: "board-card-games-02", label: "Learning a new game", text: "Explain the rules of [game] in simple terms, as if teaching a first-time player." },
          { id: "board-card-games-03", label: "Beginner strategy tips", text: "Give me beginner strategy tips for [game] to improve beyond just learning the rules." },
          { id: "board-card-games-04", label: "Two-player game options", text: "Suggest 5 good two-player games for [preference, e.g. quick, strategic, cooperative]." },
          { id: "board-card-games-05", label: "Party game ideas", text: "Suggest games for a party of [X] people that are easy to jump in and out of." },
          { id: "board-card-games-06", label: "Building a game collection", text: "Help me think through what types of games would round out a collection that currently includes [list a few games I own]." },
          { id: "board-card-games-07", label: "House rule fixes", text: "Suggest reasonable house rule variants for [game] to fix [issue, e.g. game runs too long, one strategy dominates]." },
          { id: "board-card-games-08", label: "Games for a mixed-age group", text: "Suggest board/card games appropriate for a mixed group including kids around [age] and adults." },
          { id: "board-card-games-09", label: "Standard deck card games", text: "Suggest 5 card games playable with a standard deck for [X] players." },
          { id: "board-card-games-10", label: "Pitching a game to skeptics", text: "Help me pitch [game] to friends who don't usually play board games, focused on what makes it fun." },
        ],
      },
      {
        id: "gardening-plants",
        label: "Gardening/Plants",
        prompts: [
          { id: "gardening-plants-01", label: "Plant recommendations", text: "Suggest low-maintenance plants suited to [light conditions/climate/indoor-outdoor] for a beginner." },
          { id: "gardening-plants-02", label: "Troubleshooting a struggling plant", text: "My [plant] has [symptom, e.g. yellowing leaves, drooping]. Help me think through likely causes." },
          { id: "gardening-plants-03", label: "Garden bed layout", text: "Help me plan a layout for a [size] garden bed growing [list plants], considering sun and spacing needs." },
          { id: "gardening-plants-04", label: "Seasonal task checklist", text: "Give me a seasonal to-do checklist for a [garden type] garden in [climate/season]." },
          { id: "gardening-plants-05", label: "Companion planting", text: "Suggest good companion plants for growing alongside [plant], and any plants to avoid pairing it with." },
          { id: "gardening-plants-06", label: "Pest identification help", text: "Help me think through what might be causing [pest/damage description] on my [plant], and organic treatment options." },
          { id: "gardening-plants-07", label: "Container gardening", text: "Suggest what I could realistically grow in containers on a [balcony/patio size] with [light conditions]." },
          { id: "gardening-plants-08", label: "Improving soil", text: "Suggest ways to improve [soil type/issue] for growing [plant type]." },
          { id: "gardening-plants-09", label: "Propagation help", text: "Explain how to propagate [plant] from [cutting/division/seed] as a beginner." },
          { id: "gardening-plants-10", label: "Year-round indoor plants", text: "Suggest indoor plants that stay attractive year-round for a [light level] room, and their basic care needs." },
        ],
      },
      {
        id: "cars-vehicle",
        label: "Cars/Vehicle",
        prompts: [
          { id: "cars-vehicle-01", label: "Troubleshooting a noise or issue", text: "My car is [describe symptom, e.g. making a noise when braking, shaking at highway speed]. Help me think through likely causes before I take it to a mechanic." },
          { id: "cars-vehicle-02", label: "Basic maintenance schedule", text: "Help me build a basic maintenance schedule for a [year/make/model] with [mileage]." },
          { id: "cars-vehicle-03", label: "Comparing two cars", text: "Help me think through what to compare between [car A] and [car B] for [my use case, e.g. commuting, family, towing]." },
          { id: "cars-vehicle-04", label: "Explaining a warning light", text: "Explain what a [warning light] typically means and whether it's safe to keep driving." },
          { id: "cars-vehicle-05", label: "DIY vs. mechanic", text: "Help me decide whether [repair/task] is realistic to DIY or better left to a mechanic, given [my experience level]." },
          { id: "cars-vehicle-06", label: "Road trip vehicle checklist", text: "Give me a pre-road-trip vehicle checklist for a [distance] trip." },
          { id: "cars-vehicle-07", label: "Understanding a repair estimate", text: "Help me understand this repair estimate and what questions I should ask the shop: [paste estimate]." },
          { id: "cars-vehicle-08", label: "Seasonal driving prep", text: "Suggest what I should do to prepare my car for [winter/summer] driving conditions." },
          { id: "cars-vehicle-09", label: "Fuel efficiency tips", text: "Suggest realistic ways to improve fuel efficiency for my [vehicle type/driving habits]." },
          { id: "cars-vehicle-10", label: "Explaining a car term", text: "Explain [car term, e.g. torque, all-wheel drive vs. four-wheel drive, CVT] in plain language." },
        ],
      },
      {
        id: "sports-fitness",
        label: "Sports/Fitness",
        prompts: [
          { id: "sports-fitness-01", label: "Workout plan", text: "Create a [X]-day-a-week workout plan for [goal, e.g. building strength, general fitness] at [experience level] with access to [equipment]." },
          { id: "sports-fitness-02", label: "Form check questions", text: "What are the common form mistakes to watch for when doing [exercise], and how would I know if my form is off?" },
          { id: "sports-fitness-03", label: "Modifying around an injury", text: "I have [minor limitation, e.g. sore knee]. Suggest modifications to a [workout type] routine to work around it. (Not medical advice.)" },
          { id: "sports-fitness-04", label: "Learning a new sport", text: "I'm a complete beginner at [sport]. Suggest how to get started, including basic skills to practice first." },
          { id: "sports-fitness-05", label: "Staying consistent", text: "Suggest realistic strategies for staying consistent with [fitness goal] given I struggle with [obstacle, e.g. time, motivation]." },
          { id: "sports-fitness-06", label: "Recovery routine", text: "Suggest a recovery routine after [type of intense activity]." },
          { id: "sports-fitness-07", label: "Breaking through a plateau", text: "I've plateaued on [specific goal, e.g. a lift, a running pace]. Suggest possible reasons and ways to break through." },
          { id: "sports-fitness-08", label: "Minimal-equipment home workout", text: "Design a [time]-minute workout I can do at home with just [equipment, e.g. bodyweight, one set of dumbbells]." },
          { id: "sports-fitness-09", label: "Explaining a training concept", text: "Explain [concept, e.g. progressive overload, HIIT, periodization] in plain language and how I'd apply it." },
          { id: "sports-fitness-10", label: "Training for an event", text: "Help me build a training plan to prepare for [event, e.g. a 5K, a hike] happening in [timeframe]." },
        ],
      },
      {
        id: "meditation-wellness",
        label: "Meditation/Wellness",
        prompts: [
          { id: "meditation-wellness-01", label: "Beginner meditation guide", text: "Walk me through a simple [X]-minute meditation practice for a complete beginner." },
          { id: "meditation-wellness-02", label: "Stress management ideas", text: "Suggest realistic, low-effort ways to manage stress during [specific situation, e.g. a busy work week]." },
          { id: "meditation-wellness-03", label: "Building a sustainable habit", text: "Help me design a sustainable plan to build a daily [meditation/journaling/wellness] habit, starting small." },
          { id: "meditation-wellness-04", label: "Improving a sleep routine", text: "Suggest a wind-down routine to improve sleep quality, given I struggle with [specific issue, e.g. racing thoughts, screen time before bed]." },
          { id: "meditation-wellness-05", label: "Journaling prompts", text: "Give me 10 journaling prompts for [purpose, e.g. self-reflection, gratitude, working through a hard week]." },
          { id: "meditation-wellness-06", label: "Simple breathing exercise", text: "Walk me through a simple breathing exercise I can use when feeling [anxious/overwhelmed]." },
          { id: "meditation-wellness-07", label: "Mindful transition ritual", text: "Suggest a short mindful ritual to help me transition from [work mode] to [home/rest mode]." },
          { id: "meditation-wellness-08", label: "Realistic digital detox plan", text: "Help me design a realistic plan to reduce screen time in the evenings without feeling deprived." },
          { id: "meditation-wellness-09", label: "Simple gratitude practice", text: "Suggest a simple, sustainable gratitude practice I could do daily in under 5 minutes." },
          { id: "meditation-wellness-10", label: "Explaining a wellness concept", text: "Explain [concept, e.g. mindfulness vs. meditation, the stress response] in plain, non-clinical language." },
        ],
      },
      {
        id: "photography",
        label: "Photography",
        prompts: [
          { id: "photography-01", label: "Shooting tips for a scene", text: "Give me composition and settings tips for photographing [subject, e.g. sunset landscapes, portraits, moving subjects]." },
          { id: "photography-02", label: "Gear recommendations", text: "Suggest a reasonable [budget] camera/lens setup for someone interested in [photography type]." },
          { id: "photography-03", label: "Basic editing workflow", text: "Suggest a basic editing workflow to improve [type of photo] using [editing tool]." },
          { id: "photography-04", label: "Composition self-check", text: "Give me a checklist of composition principles to evaluate my own photos against." },
          { id: "photography-05", label: "Learning manual mode", text: "Explain aperture, shutter speed, and ISO in plain terms, and how to think about adjusting them together." },
          { id: "photography-06", label: "Location scouting ideas", text: "Suggest what to look for when scouting a location for [type of shoot] near [area/type of environment]." },
          { id: "photography-07", label: "Simple lighting setup", text: "Suggest a simple lighting setup for [subject type, e.g. product photos, portraits] using accessible/affordable equipment." },
          { id: "photography-08", label: "Building a portfolio", text: "Help me think through how to organize a portfolio around [genre/theme] for [purpose, e.g. personal site, submitting to a contest]." },
          { id: "photography-09", label: "Themed photo project idea", text: "Suggest a themed personal photo project I could work on over [timeframe]." },
          { id: "photography-10", label: "Troubleshooting a shot", text: "I'm trying to capture [type of shot] but it's not working. Help me think through what might be going wrong." },
        ],
      },
      {
        id: "tech-computers",
        label: "Tech/Computers",
        prompts: [
          { id: "tech-computers-01", label: "Troubleshooting a device", text: "My [device] is [describe issue]. Help me think through likely causes and steps to try before seeking professional help." },
          { id: "tech-computers-02", label: "Buying guidance", text: "Help me think through what specs actually matter for [use case, e.g. video editing, gaming, general use] when buying a [device type]." },
          { id: "tech-computers-03", label: "Explaining a tech concept", text: "Explain [tech concept, e.g. cloud storage, VPNs, two-factor authentication] in plain language for a non-technical person." },
          { id: "tech-computers-04", label: "Organizing digital files", text: "Suggest a simple, sustainable system for organizing [type of files, e.g. photos, documents] so I can actually find them later." },
          { id: "tech-computers-05", label: "Comparing two tools", text: "Compare [tool A] and [tool B] for [use case], and help me decide which fits my needs." },
          { id: "tech-computers-06", label: "Personal cybersecurity checklist", text: "Give me a basic personal cybersecurity checklist covering passwords, accounts, and common scams to watch for." },
          { id: "tech-computers-07", label: "Speeding up a slow device", text: "Suggest realistic steps to speed up a [device type] that's running slow, before considering a replacement." },
          { id: "tech-computers-08", label: "Setting up a smart home device", text: "Help me think through what to consider when setting up [smart home device type] for the first time." },
          { id: "tech-computers-09", label: "Simple backup strategy", text: "Help me design a simple backup strategy for [type of data] that doesn't rely on just one method." },
          { id: "tech-computers-10", label: "Starting to learn to code", text: "I want to start learning [programming language] for [goal, e.g. building a website, automating tasks]. Suggest a realistic starting path." },
        ],
      },
      {
        id: "writing",
        label: "Writing",
        prompts: [
          { id: "writing-01", label: "Breaking through writer's block", text: "I'm stuck writing [type of piece] about [topic]. Suggest a few different angles or starting points to break through the block." },
          { id: "writing-02", label: "Feedback on a draft", text: "Give me structured feedback on this piece of writing, focused on [aspect, e.g. clarity, pacing, tone]: [paste text]." },
          { id: "writing-03", label: "Exploring tone and voice", text: "Help me experiment with different tones for this piece — show me [X] versions in different voices: [paste short excerpt]." },
          { id: "writing-04", label: "Outline help", text: "Help me build an outline for a [type of piece, e.g. short story, essay, blog post] about [topic]." },
          { id: "writing-05", label: "Character development", text: "Help me develop a character who [rough description], including motivations, flaws, and a defining contradiction." },
          { id: "writing-06", label: "Creative writing practice prompt", text: "Give me a creative writing prompt in the genre of [genre] to practice with today." },
          { id: "writing-07", label: "Tightening a paragraph", text: "Suggest ways to tighten and improve the flow of this paragraph without losing its meaning: [paste paragraph]." },
          { id: "writing-08", label: "World-building questions", text: "Give me a list of world-building questions to think through for a story set in [setting concept]." },
          { id: "writing-09", label: "Building a writing habit", text: "Suggest realistic ways to build a sustainable writing habit given I have [time constraint]." },
          { id: "writing-10", label: "Title/headline brainstorm", text: "Brainstorm 10 possible titles for a piece about [topic/theme], varying in tone from serious to playful." },
        ],
      },
      {
        id: "making-music",
        label: "Making Music",
        prompts: [
          { id: "making-music-01", label: "Beginner practice plan", text: "I'm a beginner on [instrument]. Suggest a realistic practice plan for my first month." },
          { id: "making-music-02", label: "Songwriting starting point", text: "Give me a chord progression and a mood/theme to start writing a song around." },
          { id: "making-music-03", label: "Daily practice routine", text: "Help me design a [X]-minute daily practice routine for [instrument] that balances technique and material I enjoy." },
          { id: "making-music-04", label: "Explaining a music theory concept", text: "Explain [music theory concept, e.g. modes, chord inversions, circle of fifths] in plain, practical terms." },
          { id: "making-music-05", label: "Breaking through a skill plateau", text: "I've plateaued learning [skill/technique] on [instrument]. Suggest exercises or approaches to break through." },
          { id: "making-music-06", label: "Simple home recording setup", text: "Suggest a simple, affordable home recording setup for [type of music/instrument]." },
          { id: "making-music-07", label: "Learning a song by ear", text: "Give me a step-by-step approach to learning to play [type of song] by ear." },
          { id: "making-music-08", label: "Exploring a new genre", text: "I mainly play/listen to [genre]. Suggest a different genre to explore that would still build useful skills." },
          { id: "making-music-09", label: "Lyric writing help", text: "Help me brainstorm lyric ideas around the theme of [theme/emotion], in the style of [reference, if any]." },
          { id: "making-music-10", label: "Building a setlist", text: "Help me build a setlist for [context, e.g. an open mic, a small gig] balancing energy and pacing across [X] songs." },
        ],
      },
    ],
  },
};
